In [1]:
import numpy as np
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

In [2]:
a.ndim

2

In [3]:
a.size

6

In [4]:
a.shape

(2, 3)

In [5]:
a.shape[2-1]

3

In [6]:
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
b = [[1. ,2. ,3.], [4. ,5. ,6]]
c = np.block([[b, b], [b, b]])
d = np.block([[a, a], [a, a]])
print(c,c.shape)
print(d,d.shape)

[[[[1. 2. 3.]
   [4. 5. 6.]]

  [[1. 2. 3.]
   [4. 5. 6.]]]


 [[[1. 2. 3.]
   [4. 5. 6.]]

  [[1. 2. 3.]
   [4. 5. 6.]]]] (2, 2, 2, 3)
[[1. 2. 3. 1. 2. 3.]
 [4. 5. 6. 4. 5. 6.]
 [1. 2. 3. 1. 2. 3.]
 [4. 5. 6. 4. 5. 6.]] (4, 6)


In [8]:
a[-1]

array([4., 5., 6.])

In [9]:
a[1, 2]

6.0

In [10]:
a[1, :]

array([4., 5., 6.])

In [11]:
a[-2:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
b = np.arange(30)
b = b.reshape((5,6))
print(b)
b[0:3, 4:6]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 4,  5],
       [10, 11],
       [16, 17]])

In [13]:
b[np.ix_([1, 3, 4], [0, 2])]

array([[ 6,  8],
       [18, 20],
       [24, 26]])

In [14]:
b[0:6:2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [15]:
b[ ::2,:]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29]])

In [16]:
b[::-1,:]

array([[24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [17]:
b[np.r_[:len(b),0:2]]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [18]:
b.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [19]:
x = b + 1j
print(x)
x.conj().T

[[ 0.+1.j  1.+1.j  2.+1.j  3.+1.j  4.+1.j  5.+1.j]
 [ 6.+1.j  7.+1.j  8.+1.j  9.+1.j 10.+1.j 11.+1.j]
 [12.+1.j 13.+1.j 14.+1.j 15.+1.j 16.+1.j 17.+1.j]
 [18.+1.j 19.+1.j 20.+1.j 21.+1.j 22.+1.j 23.+1.j]
 [24.+1.j 25.+1.j 26.+1.j 27.+1.j 28.+1.j 29.+1.j]]


array([[ 0.-1.j,  6.-1.j, 12.-1.j, 18.-1.j, 24.-1.j],
       [ 1.-1.j,  7.-1.j, 13.-1.j, 19.-1.j, 25.-1.j],
       [ 2.-1.j,  8.-1.j, 14.-1.j, 20.-1.j, 26.-1.j],
       [ 3.-1.j,  9.-1.j, 15.-1.j, 21.-1.j, 27.-1.j],
       [ 4.-1.j, 10.-1.j, 16.-1.j, 22.-1.j, 28.-1.j],
       [ 5.-1.j, 11.-1.j, 17.-1.j, 23.-1.j, 29.-1.j]])

In [20]:
c = np.ones(6)
c = c.reshape((3,2))
c *= 2
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
print(a @ c)
np.dot(a,c)

[[12. 12.]
 [30. 30.]]


array([[12., 12.],
       [30., 30.]])

In [21]:
c = c.reshape(2,3)
print(a * c)
np.multiply(a,c)


[[ 2.  4.  6.]
 [ 8. 10. 12.]]


array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [22]:
a/c

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [23]:
a**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
c = a/2
c > 0.5



array([[False,  True,  True],
       [ True,  True,  True]])

In [25]:
np.nonzero(c > 0.5)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [26]:
print(c)
v = np.array([0,1])
c[:,np.nonzero(v > 0.5)[0]]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


array([[1. ],
       [2.5]])

In [27]:
print(c)
v = np.array([0,1,0])
c[:, v.T > 0.5]

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


array([[1. ],
       [2.5]])

In [28]:
d = c
d[d < 1.5]=0
d

array([[0. , 0. , 1.5],
       [2. , 2.5, 3. ]])

In [29]:
d = c
d * (d > 0.5)

array([[0. , 0. , 1.5],
       [2. , 2.5, 3. ]])

In [30]:
d[:] = 3
d

array([[3., 3., 3.],
       [3., 3., 3.]])

In [31]:
x = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
y = x.copy()
y

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
y = x[1, :].copy()
y

array([4., 5., 6.])

In [33]:
y = x.flatten()
y

array([1., 2., 3., 4., 5., 6.])

In [34]:
print(np.arange(10.) )
print(np.r_[:10.])
np.r_[:9:10j]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [35]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [36]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [38]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
np.diag(a)

array([1., 5.])

In [41]:
v = np.array([1. ,2. ,3., 4. ,5. ,6.])
np.diag(v, 0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 6.]])

In [42]:
rng = np.random.default_rng(42)
print(rng.random((3, 4)))
np.random.rand(3, 4)

[[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802 0.92676499]]


array([[0.42196616, 0.04415236, 0.59126324, 0.03820889],
       [0.40424991, 0.56189035, 0.69562858, 0.87668152],
       [0.12695111, 0.20820623, 0.29535498, 0.19792265]])

In [43]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [44]:
print(np.mgrid[0:9.,0:6.] )
np.meshgrid(np.r_[0:9.],np.r_[0:6.])

[[[0. 0. 0. 0. 0. 0.]
  [1. 1. 1. 1. 1. 1.]
  [2. 2. 2. 2. 2. 2.]
  [3. 3. 3. 3. 3. 3.]
  [4. 4. 4. 4. 4. 4.]
  [5. 5. 5. 5. 5. 5.]
  [6. 6. 6. 6. 6. 6.]
  [7. 7. 7. 7. 7. 7.]
  [8. 8. 8. 8. 8. 8.]]

 [[0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]
  [0. 1. 2. 3. 4. 5.]]]


[array([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])]

In [45]:
print(np.ogrid[0:9.,0:6.])
np.ix_(np.r_[0:9.],np.r_[0:6.])

[array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.]]), array([[0., 1., 2., 3., 4., 5.]])]


(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]]))

In [46]:
print(np.meshgrid([1,2,4],[2,4,5]))
np.ix_([1,2,4],[2,4,5])


[array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]]), array([[2, 2, 2],
       [4, 4, 4],
       [5, 5, 5]])]


(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [47]:
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
np.tile(a,(3,2))


array([[1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.],
       [1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.],
       [1., 2., 3., 1., 2., 3.],
       [4., 5., 6., 4., 5., 6.]])

In [48]:
b = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
b += 6
print(np.concatenate((a,b),1))
print(np.hstack((a,b)) )
print(np.column_stack((a,b)))
np.c_[a,b]

[[ 1.  2.  3.  7.  8.  9.]
 [ 4.  5.  6. 10. 11. 12.]]
[[ 1.  2.  3.  7.  8.  9.]
 [ 4.  5.  6. 10. 11. 12.]]
[[ 1.  2.  3.  7.  8.  9.]
 [ 4.  5.  6. 10. 11. 12.]]


array([[ 1.,  2.,  3.,  7.,  8.,  9.],
       [ 4.,  5.,  6., 10., 11., 12.]])

In [49]:
print(np.concatenate((a,b)))
print(np.vstack((a,b)) )
np.r_[a,b]


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [50]:
a.max()

6.0

In [51]:
a.max(0)

array([4., 5., 6.])

In [52]:
a.max(1)

array([3., 6.])

In [53]:
np.maximum(a, b)

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [54]:
np.linalg.norm(a)

9.539392014169456

In [55]:
np.logical_and(a,b)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [56]:
np.logical_or(a,b)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [57]:
c = 5
d = 6
c & d

4

In [58]:
c | d

7

In [59]:
a = np.array([[1,2],[3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [60]:
np.linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
np.linalg.matrix_rank(a)

2

In [62]:
b = a * 2
print(np.linalg.lstsq(a, b))
np.linalg.solve(a, b)

(array([[ 2.00000000e+00, -2.00619055e-16],
       [-1.20371433e-15,  2.00000000e+00]]), array([], dtype=float64), 2, array([5.4649857 , 0.36596619]))


C:\Users\gaozh\AppData\Local\Temp\ipykernel_35200\1981278641.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  print(np.linalg.lstsq(a, b))


array([[2.00000000e+00, 0.00000000e+00],
       [1.66533454e-16, 2.00000000e+00]])

In [63]:
U, S, Vh = np.linalg.svd(a)
V = Vh.T
V


array([[-0.57604844,  0.81741556],
       [-0.81741556, -0.57604844]])

In [64]:
c = a@a.T
b = np.linalg.cholesky(c)
b

array([[2.23606798, 0.        ],
       [4.91934955, 0.89442719]])

In [65]:
D,V = np.linalg.eig(a)
D,V

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [66]:
import scipy.linalg
b = 2 * a
D,V = scipy.linalg.eig(a, b)
D,V

(array([0.5+0.j, 0.5+0.j]),
 array([[-1., -0.],
        [-0., -1.]]))

In [67]:
from scipy.sparse.linalg import eigs
id = np.eye(13)
D,V = eigs(id, k=6)
D,V

(array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]),
 array([[-6.36570140e-02+0.j, -5.10338949e-01+0.j, -2.41114702e-01+0.j,
         -1.75693003e-01+0.j, -2.23870980e-02+0.j, -4.07173713e-01+0.j],
        [ 1.59704732e-01+0.j, -1.29260460e-01+0.j,  4.86868106e-02+0.j,
          1.20087412e-01+0.j,  1.38068260e-03+0.j, -1.71405907e-01+0.j],
        [ 6.60250982e-03+0.j, -4.86598824e-01+0.j, -7.84283251e-02+0.j,
         -2.30816803e-01+0.j,  5.83807196e-02+0.j,  2.11956406e-01+0.j],
        [ 3.92586856e-01+0.j,  2.09875576e-01+0.j,  7.03791822e-02+0.j,
          1.28845635e-01+0.j,  6.23330909e-02+0.j, -3.07309819e-01+0.j],
        [-1.54796514e-02+0.j,  1.38356649e-02+0.j,  5.41512679e-02+0.j,
         -1.11535127e-01+0.j, -7.35643816e-03+0.j, -3.70210392e-02+0.j],
        [ 2.81137291e-04+0.j,  4.10108881e-04+0.j, -8.62979063e-04+0.j,
         -1.17604409e-03+0.j, -9.89976762e-01+0.j,  5.85961216e-03+0.j],
        [-2.75531151e-02+0.j, -1.78830252e-01+0.j, -6.40627883e-02+0.j,


In [68]:
Q,R = np.linalg.qr(a)
Q,R

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))

In [69]:
P,L,U = scipy.linalg.lu(a)
P,L,U

(array([[0., 1.],
        [1., 0.]]),
 array([[1.        , 0.        ],
        [0.33333333, 1.        ]]),
 array([[3.        , 4.        ],
        [0.        , 0.66666667]]))

In [70]:
scipy.sparse.linalg.cg

<function scipy.sparse.linalg.isolve.iterative.cg(A, b, x0=None, tol=1e-05, maxiter=None, M=None, callback=None, atol=None)>

In [71]:
np.fft.fft(a)

array([[ 3.+0.j, -1.+0.j],
       [ 7.+0.j, -1.+0.j]])

In [72]:
np.fft.ifft(a)

array([[ 1.5+0.j, -0.5+0.j],
       [ 3.5+0.j, -0.5+0.j]])

In [73]:
print(np.sort(a))
a.sort(axis=0)

[[1 2]
 [3 4]]


In [74]:
print(np.sort(a, axis = 1))
a.sort(axis = 1)

[[1 2]
 [3 4]]


In [75]:
I = np.argsort(a[:, 0])
b = a[I,:]
b

array([[1, 2],
       [3, 4]])

In [76]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
m, c = np.linalg.lstsq(A, y, rcond=None)[0]
m, c

(0.9999999999999997, -0.9499999999999987)

In [77]:
from scipy import signal
x = np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
signal.resample(y, 100)

array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [78]:
np.unique(a)


array([1, 2, 3, 4])

In [79]:
a.squeeze()

array([[1, 2],
       [3, 4]])